version: 0.2
phases:
  pre_build:
    commands:
      - REPOSITORY_HOST=595508394202.dkr.ecr.us-west-2.amazonaws.com
      - REPOSITORY_URI=$REPOSITORY_HOST/syn-bot
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - tar --exclude .git -cvf syn-bot.tar .
      - echo running docker build
      - DOCKER_ID=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-west-2:595508394202:secret:docker-credentials-X0hFW8 | jq -r '.SecretString' | jq -r '.DOCKER_ID')
      - aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-west-2:595508394202:secret:docker-credentials-X0hFW8 | jq -r '.SecretString' | jq -r '.DOCKER_PASSWORD' | docker login --username $DOCKER_ID --password-stdin
      - docker build -t $REPOSITORY_URI:latest .
      - echo not docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:latest
      - echo not tagging with $REPOSITORY_URI:$IMAGE_TAG so ECR lifecycle can eventually delete
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password  | docker login --username AWS --password-stdin $REPOSITORY_HOST
      - docker push $REPOSITORY_URI:latest

