version: 0.2
phases:
  install:
    runtime-versions:
        ruby: 2.7
  pre_build:
    commands:
      - REPOSITORY_HOST=595508394202.dkr.ecr.us-west-2.amazonaws.com
      - REPOSITORY_URI=$REPOSITORY_HOST/syn-bot
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - aws ecr get-login-password  | docker login --username AWS --password-stdin $REPOSITORY_HOST
      - rbenv versions | cut -c3- | grep '2.7' > .ruby-version
      - bundle config set without development
      - bundle config set path vendor/bundle
      - bundle install
      - bundle exec rspec -fd spec/ --format RspecJunitFormatter --out out/report.xml
  build:
    commands:
      - ./apply-patches.sh
      - tar --exclude .git -cf syn-bot.tar .
      - echo running docker build
      - docker build -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:latest
reports:
    rspec_reports:
        files:
            - report.xml
        base-directory: out
        file-format: JunitXml
