discord_application_id: 856369764729618432
discord_guild_id: 1001238356648271923
discord_channel: 1001243339976351895
discord_hook: 1023304991294881908
fqdn: bridgesyndicate.gg
icon_thumb: "https://s3.us-west-2.amazonaws.com/www.bridgesyndicate.gg/bridge-icon-128x128-transparent.png"
show_elo: true
include_duel_options: true
admin_discord_id: 246107858712788993
welcome_message_title: ''
how_to_verify_description: ''
secrets_manager_klass: 'Secrets'
season_klass: Season